// Code generated by GCG. DO NOT EDIT.
// Go Code Generator 0.0.7 (https://github.com/OhYee/gcg)

package fp

import ()

// AnyString return true if any of values is matched
func AnyString(f func(string) bool, input []string) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// AnyInt return true if any of values is matched
func AnyInt(f func(int) bool, input []int) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// AnyInt8 return true if any of values is matched
func AnyInt8(f func(int8) bool, input []int8) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// AnyInt16 return true if any of values is matched
func AnyInt16(f func(int16) bool, input []int16) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// AnyInt32 return true if any of values is matched
func AnyInt32(f func(int32) bool, input []int32) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// AnyInt64 return true if any of values is matched
func AnyInt64(f func(int64) bool, input []int64) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// AnyUint8 return true if any of values is matched
func AnyUint8(f func(uint8) bool, input []uint8) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// AnyUint16 return true if any of values is matched
func AnyUint16(f func(uint16) bool, input []uint16) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// AnyUint32 return true if any of values is matched
func AnyUint32(f func(uint32) bool, input []uint32) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// AnyUint64 return true if any of values is matched
func AnyUint64(f func(uint64) bool, input []uint64) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// AnyFloat32 return true if any of values is matched
func AnyFloat32(f func(float32) bool, input []float32) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// AnyFloat64 return true if any of values is matched
func AnyFloat64(f func(float64) bool, input []float64) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// AnyByte return true if any of values is matched
func AnyByte(f func(byte) bool, input []byte) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}

// Any return true if any of values is matched
func Any(f func(any) bool, input []any) (output bool) {
	output = false
	for _, data := range input {
		output = output || f(data)
		if output {
			break
		}
	}
	return
}
